name: CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE: ghcr.io/hello-python-api:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Python deps
      run: |
        pip install -r requirements.txt
        pip install pytest flake8 httpx

    - name: Lint with Flake8
      run: flake8 app

    - name: Test using Pytest
      run: PYTHONPATH=. pytest

    - name: Build image
      run: docker build -t $IMAGE .

    - name: Trivy Securty scan for images
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE }}
        severity: HIGH,CRITICAL
        exit-code: 1

    - name: Trivy Securty scan for Files
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .
        severity: HIGH,CRITICAL
        exit-code: 1

    - name: Generate SBOM
      uses: anchore/syft@v1.40.0
      with:
        image: ${{ env.IMAGE }}
        output: spdx-json=sbom.spdx.json