name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write   # Mandatory for cosign keyless

env:
  IMAGE: hello-python-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Python deps
      run: |
        pip install -r requirements.txt
        pip install pytest flake8 httpx

    - name: Lint with Flake8
      run: flake8 app

    - name: Test using Pytest
      run: PYTHONPATH=. pytest

    - name: Build image
      run: docker build -t $IMAGE .

    - name: Trivy Securty scan for images
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE }}
        severity: HIGH,CRITICAL
        exit-code: 1

    - name: Trivy Securty scan for Files
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .
        severity: HIGH,CRITICAL
        exit-code: 1

    - name: Install Syft CLI
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Run Syft and generate sbom file
      run: |
        /usr/local/bin/syft ${{ env.IMAGE }} -o spdx-json >  image-sbom.spdx.json

    - name: Upload SBOM file
      uses: actions/upload-artifact@v4
      with:
        name: image-sbom
        path: image-sbom.spdx.json

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    #- name: Push image to DockerHub
    #  run: docker push $IMAGE
    - name: Build and Push Image
      id: build
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          docker.io/${{ vars.DOCKER_REGISTRY_USER }}/${{ env.IMAGE }}:latest

    - name: Sign image (Cosign keyless)
      uses: sigstore/cosign-installer@v3


    - name: Login to Docker Hub for Cosign
      env:
        COSIGN_DOCKER_USERNAME: ${{ vars.DOCKER_REGISTRY_USER  }}
        COSIGN_DOCKER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      run: echo "Cosign auth configured"


    - name: Sign image with Cosign (keyless)
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign --yes \
          docker.io/${{ vars.DOCKER_REGISTRY_USER }}/${{ env.IMAGE }}@${{ steps.build.outputs.digest }}

    - name: Verify the container image signature
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign verify \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com \
          --certificate-identity-regexp "https://github.com/${{ github.repository }}/.github/workflows/.*" \
          docker.io/${{ vars.DOCKER_REGISTRY_USER }}/${{ env.IMAGE }}:latest

